//! Everything you need to run an
//! [Ising model](https://en.wikipedia.org/wiki/Ising_model) simulation.
//! Despite its simplicity, the simulation allows us to observe an interesting
//! physical phenomenon - phase transition. [`ndarray`][ndarray]'s arrays
//! are used to store the spin lattice and perform computations. The lattice
//! behaves like a torus - spins on the opposite edges are considered each
//! other's neighbors. Spin array either be generated by [`rand`][rand]s
//! RNG or provided by the user.

pub mod lattice;
pub mod prelude;
